/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author edu-pop
 */
public class telaCalc extends javax.swing.JFrame {

    /**
     * Creates new form telaCalc
     */
    public telaCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entryNumero = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lblRestoPor2 = new javax.swing.JLabel();
        lblElevadoAoCubo = new javax.swing.JLabel();
        lblRaizQuadrada = new javax.swing.JLabel();
        lblRaizCubica = new javax.swing.JLabel();
        lblValorAbsoluto = new javax.swing.JLabel();
        resRestoPor2 = new javax.swing.JLabel();
        resElevadoAoCubo = new javax.swing.JLabel();
        resRaizQuadrada = new javax.swing.JLabel();
        resRaizCubica = new javax.swing.JLabel();
        resValorAbsoluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jLabel1.setText("Informe um valor");

        entryNumero.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        entryNumero.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblRestoPor2.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        lblRestoPor2.setText("     ");

        lblElevadoAoCubo.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        lblElevadoAoCubo.setText("     ");

        lblRaizQuadrada.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        lblRaizQuadrada.setText("     ");

        lblRaizCubica.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        lblRaizCubica.setText("     ");

        lblValorAbsoluto.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        lblValorAbsoluto.setText("     ");

        resRestoPor2.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        resRestoPor2.setForeground(new java.awt.Color(51, 153, 0));
        resRestoPor2.setText(" ");

        resElevadoAoCubo.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        resElevadoAoCubo.setForeground(new java.awt.Color(51, 153, 0));
        resElevadoAoCubo.setText(" ");

        resRaizQuadrada.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        resRaizQuadrada.setForeground(new java.awt.Color(51, 153, 0));
        resRaizQuadrada.setText(" ");

        resRaizCubica.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        resRaizCubica.setForeground(new java.awt.Color(51, 153, 0));
        resRaizCubica.setText(" ");

        resValorAbsoluto.setFont(new java.awt.Font("Fira Sans", 1, 15)); // NOI18N
        resValorAbsoluto.setForeground(new java.awt.Color(51, 153, 0));
        resValorAbsoluto.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(entryNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValorAbsoluto, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lblRaizQuadrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblElevadoAoCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRestoPor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRaizCubica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resRestoPor2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(resElevadoAoCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resRaizQuadrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resRaizCubica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resValorAbsoluto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entryNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRestoPor2)
                        .addGap(18, 18, 18)
                        .addComponent(lblElevadoAoCubo)
                        .addGap(18, 18, 18)
                        .addComponent(lblRaizQuadrada))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resRestoPor2)
                        .addGap(18, 18, 18)
                        .addComponent(resElevadoAoCubo)
                        .addGap(18, 18, 18)
                        .addComponent(resRaizQuadrada)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(resRaizCubica)
                        .addGap(18, 18, 18)
                        .addComponent(resValorAbsoluto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblRaizCubica)
                        .addGap(18, 18, 18)
                        .addComponent(lblValorAbsoluto)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        float numero = Float.parseFloat(entryNumero.getValue().toString()); //Capturar número de entrada
        
        lblRestoPor2.setText("Resto da Divisão de " + numero + " por 2");
        lblElevadoAoCubo.setText(numero + " ao cubo");
        lblRaizQuadrada.setText("Raiz Quadrada de " + numero);
        lblRaizCubica.setText("Raiz Cubica de " + numero);
        lblValorAbsoluto.setText("Valor Absoluto ");
        
        //Calcular e imprimir o resto da divisão do número informado por 2
        float restoPor2 = numero % 2;
        resRestoPor2.setText(String.format("%.2f", restoPor2));
        
        //Calcular e imprimir o número digitado ao cubo
        float aoCubo = (float) Math.pow(numero, 3);
        resElevadoAoCubo.setText(String.format("%.2f", aoCubo));
        
        //Calcular a Raiz Quadrada do número informado
        float raizQuadrada = (float) Math.sqrt(numero);
        resRaizQuadrada.setText(String.format("%.2f", raizQuadrada));
        
        //Calcular a Raiz Cúbica do número informado
        float raizCubica = (float) Math.cbrt(numero);
        resRaizCubica.setText(String.format("%.2f", raizCubica));
        
        //Calcular o valor absoluto do número informado
        int valorAbsoluto = (int) Math.abs(numero);
        resValorAbsoluto.setText(Integer.toString(valorAbsoluto));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner entryNumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblElevadoAoCubo;
    private javax.swing.JLabel lblRaizCubica;
    private javax.swing.JLabel lblRaizQuadrada;
    private javax.swing.JLabel lblRestoPor2;
    private javax.swing.JLabel lblValorAbsoluto;
    private javax.swing.JLabel resElevadoAoCubo;
    private javax.swing.JLabel resRaizCubica;
    private javax.swing.JLabel resRaizQuadrada;
    private javax.swing.JLabel resRestoPor2;
    private javax.swing.JLabel resValorAbsoluto;
    // End of variables declaration//GEN-END:variables
}
